### ISSUE TITLE
A server must not mask any frames that it sends to the client. Upon logging in

### ISSUE THREAD

**Issue by Emmerlord** [Terreii/andromeda-viewer#18]
WebSocket connection to 'ws://127.0.0.1:8000/' failed: A server must not mask any frames that it sends to the client.

**Comment by Emmerlord** [comment]
This is where it occurs 
this.websocket = new window.WebSocket(
    window.location.origin.replace(/^http/, 'ws') // http -> ws  &  https -> wss
  )

**Comment by Terreii** [comment]
Thanks for the bug-report!
I have replicated the error in Chrome and Safari both with http/ws and https/wss. Firefox seams fine ...

**Comment by Terreii** [comment]
The problem is discussed in https://github.com/websockets/ws/issues/538 a server must not mask data send to clients.
