### ISSUE TITLE
Can not log in if user has no friends

### ISSUE THREAD

**Issue by Sandbox5913** [Terreii/andromeda-viewer#212]
TypeError: Cannot read property 'map' of undefined
    at friends (friendsReducer.js:16)

" return action.sessionInfo['buddy-list'].map(friend => { . "

**Comment by Terreii** [comment]
Thank you for your bug!

I didn't expect, that there will be no `buddy-list` when the an avatar has no friends!

**Comment by Terreii** [comment]
It should work now!
