### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by LifeGold** [Terreii/andromeda-viewer#29]
Hi. You to ask You to do a full installation guide. And the next question, perhaps as something to combine with OpenSim?

**Comment by Terreii** [comment]
Hi.
Thanks for your bug reports!
Your request for a installation guide is in the pull request #30. Please let me know how it is.

**Comment by Terreii** [comment]
Work for connecting to openSIM happens in #31.

**Comment by LifeGold** [comment]
Hi, wanted to ask you to do a detailed description for installing the client on Windows. And still can't test because Windows was unable to install. Wanted to ask if this is the client for example to sign a folder in Russian?

**Comment by Terreii** [comment]
Hi! The installation guide was merged on 23 Apr. Could you review it?
If there is nothing unclear left, I would like close this issue.

**Comment by Terreii** [comment]
Close do to inactivity.
It is seen as fixed.
If this issue still exist, please comment. It will then be reopened.
